# fly.toml app configuration file generated for wungus-polished-leaf-9219 on 2025-02-17T22:43:29-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wungus-polished-leaf-9219'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
